console.log(`colors.js loaded`);

const colors = [
  {
    name: "Basic Colors",
    colors: [
      {
        name: "White",
        hex: "#FFFFFF",
        rgb: "rgb(255, 255, 255)",
        hsl: "hsl(0, 0%, 100%)",
        text: "#000000",
      },
      {
        name: "Black",
        hex: "#000000",
        rgb: "rgb(0, 0, 0)",
        hsl: "hsl(0, 0%, 0%)",
        text: "#FFFFFF",
      },
      {
        name: "Gray",
        hex: "#888888",
        rgb: "rgb(136, 136, 136)",
        hsl: "hsl(0, 0%, 53%)",
        text: "#000000",
      },
      {
        name: "Red",
        hex: "#FF0000",
        rgb: "rgb(255, 0, 0)",
        hsl: "rgb(255, 0, 0)",
        text: "#FFFFFF",
      },
      {
        name: "Yellow",
        hex: "#FFFF00",
        rgb: "rgb(255, 255, 0)",
        hsl: "hsl(60, 100%, 50%)",
        text: "#000000",
      },
      {
        name: "Green",
        hex: "#00FF00",
        rgb: "rgb(0, 255, 0)",
        hsl: "hsl(120, 100%, 50%)",
        text: "#000000",
      },
      {
        name: "Cyan",
        hex: "#00FFFF",
        rgb: "rgb(0, 255, 255)",
        hsl: "hsl(180, 100%, 50%)",
        text: "#000000",
      },
      {
        name: "Blue",
        hex: "#0000FF",
        rgb: "rgb(0, 0, 255)",
        hsl: "hsl(240, 100%, 50%)",
        text: "#FFFFFF",
      },
      {
        name: "Magenta",
        hex: "#FF00FF",
        rgb: "rgb(255, 0, 255)",
        hsl: "hsl(300, 100%, 50%)",
        text: "#FFFFFF",
      },
    ],
  },
  {
    name: "Pokémon Colors",
    colors: [
      {
        name: "Bug",
        hex: "#A8B821",
        rgb: "rgb(168, 184, 33)",
        hsl: "hsl(66, 70%, 43%)",
        text: "#000000",
      },
      {
        name: "Dark",
        hex: "#6F5848",
        rgb: "rgb(111, 88, 72)",
        hsl: "hsl(25, 21%, 36%)",
        text: "#FFFFFF",
      },
      {
        name: "Dragon",
        hex: "#7038F9",
        rgb: "rgb(112, 56, 249)",
        hsl: "hsl(257, 94%, 60%)",
        text: "#FFFFFF",
      },
      {
        name: "Electric",
        hex: "#F8D030",
        rbg: "rgb(248, 208, 48)",
        hsl: "hsl(48, 93%, 58%)",
        text: "#000000",
      },
      {
        name: "Fairy",
        hex: "#FFAEC9",
        rgb: "rgb(255, 174, 201)",
        hsl: "hsl(340, 100%, 84%)",
        text: "#000000",
      },
      {
        name: "Fighting",
        hex: "#C03028",
        rgb: "rgb(192, 48, 40)",
        hsl: "hsl(3, 66%, 45%)",
        text: "#FFFFFF",
      },
      {
        name: "Fire",
        hex: "#F07F2F",
        rgb: "rgb(240, 127, 47)",
        hsl: "hsl(25, 87%, 56%)",
        text: "#000000",
      },
      {
        name: "Flying",
        hex: "#A890F0",
        rgb: "rgb(168, 144, 240)",
        hsl: "hsl(255, 76%, 75%)",
        text: "#000000",
      },
      {
        name: "Ghost",
        hex: "#715899",
        rgb: "rgb(113, 88, 153)",
        hsl: "hsl(263, 27%, 47%)",
        text: "#FFFFFF",
      },
      {
        name: "Grass",
        hex: "#78C750",
        rgb: "rgb(120, 199, 80)",
        hsl: "hsl(100, 52%, 55%)",
        text: "#000000",
      },
      {
        name: "Ground",
        hex: "#DEBF67",
        rgb: "rgb(222, 191, 103)",
        hsl: "hsl(44, 64%, 64%)",
        text: "#000000",
      },
      {
        name: "Ice",
        hex: "#98D8D8",
        rgb: "rgb(152, 216, 216)",
        hsl: "hsl(180, 45%, 72%)",
        text: "#000000",
      },
      {
        name: "Normal",
        hex: "#A9A878",
        rbg: "rgb(169, 168, 120)",
        hsl: "hsl(59, 22%, 57%)",
        text: "#000000",
      },
      {
        name: "Poison",
        hex: "#A040A1",
        rgb: "rgb(160, 64, 161)",
        hsl: "hsl(299, 43%, 44%)",
        text: "#FFFFFF",
      },
      {
        name: "Psychic",
        hex: "#F85788",
        rgb: "rgb(248, 87, 136)",
        hsl: "hsl(342, 92%, 66%)",
        text: "#FFFFFF",
      },
      {
        name: "Rock",
        hex: "#B89F38",
        rgb: "rgb(184, 159, 56)",
        hsl: "hsl(48, 53%, 47%)",
        text: "#FFFFFF",
      },
      {
        name: "Steel",
        hex: "#B8B8D0",
        rgb: "rgb(184, 184, 208)",
        hsl: "hsl(240, 20%, 77%)",
        text: "#000000",
      },
      {
        name: "Water",
        hex: "#6890F0",
        rgb: "rgb(104, 144, 240)",
        hsl: "hsl(222, 82%, 67%)",
        text: "#000000",
      },
    ],
  },
  {
    name: "Bootstrap Colors",
    colors: [
      {
        name: "Blue (Primary)",
        hex: "#007BFF",
        rgb: "",
        hsl: "",
        text: "#FFFFFF",
      },
      {
        name: "Indigo",
        hex: "#6610F2",
        rgb: "",
        hsl: "",
        text: "#FFFFFF",
      },
      {
        name: "Purple",
        hex: "#6F42C1",
        rgb: "",
        hsl: "",
        text: "#FFFFFF",
      },
      {
        name: "Pink",
        hex: "#E83E8C",
        rgb: "",
        hsl: "",
        text: "#FFFFFF",
      },
      {
        name: "Red (Danger)",
        hex: "#DC3545",
        rgb: "",
        hsl: "",
        text: "#FFFFFF",
      },
      {
        name: "Orange",
        hex: "#FD7E14",
        rgb: "",
        hsl: "",
        text: "#000000",
      },
      {
        name: "Yellow (Warning)",
        hex: "#FFC107",
        rgb: "",
        hsl: "",
        text: "#000000",
      },
      {
        name: "Green (Success)",
        hex: "#28A745",
        rgb: "",
        hsl: "",
        text: "#000000",
      },
      {
        name: "Teal",
        hex: "#20C997",
        rgb: "",
        hsl: "",
        text: "#000000",
      },
      {
        name: "Cyan (Info)",
        hex: "#17A2B8",
        rgb: "",
        hsl: "",
        text: "#FFFFFF",
      },
      {
        name: "Gray-100 (Light)",
        hex: "#F8F9FA",
        rgb: "",
        hsl: "",
        text: "#000000",
      },
      {
        name: "Gray-200",
        hex: "#E9ECEF",
        rgb: "",
        hsl: "",
        text: "#000000",
      },
      {
        name: "Gray-300",
        hex: "#DEE2E6",
        rgb: "",
        hsl: "",
        text: "#000000",
      },
      {
        name: "Gray-400",
        hex: "#CED4DA",
        rgb: "",
        hsl: "",
        text: "#000000",
      },
      {
        name: "Gray-500",
        hex: "#ADB5BD",
        rgb: "",
        hsl: "",
        text: "#000000",
      },
      {
        name: "Gray-600 (Secondary)",
        hex: "#6C757D",
        rgb: "",
        hsl: "",
        text: "#FFFFFF",
      },
      {
        name: "Gray-700",
        hex: "#495057",
        rgb: "",
        hsl: "",
        text: "#FFFFFF",
      },
      {
        name: "Gray-800",
        hex: "#343A40",
        rgb: "",
        hsl: "",
        text: "#FFFFFF",
      },
      {
        name: "Gray-900 (Dark)",
        hex: "#212529",
        rgb: "",
        hsl: "",
        text: "#FFFFFF",
      },
    ],
  },
  {
    name: "Material Colors",
    colors: [
      {
        name: "Grays",
        swatches: [
          {
            name: "Gray 50",
            hex: "#fafafa",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Gray 100",
            hex: "#f5f5f5",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Gray 200",
            hex: "#eeeeee",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Gray 300",
            hex: "#e0e0e0",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Gray 400",
            hex: "#bdbdbd",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Gray 500",
            hex: "#9e9e9e",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Gray 600",
            hex: "#757575",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Gray 700",
            hex: "#616161",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Gray 800",
            hex: "#424242",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Gray 900",
            hex: "#212121",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Reds",
        swatches: [
          {
            name: "Red 50",
            hex: "#ffebee",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Red 100",
            hex: "#ffcdd2",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Red 200",
            hex: "#ef9a9a",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Red 300",
            hex: "#e57373",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Red 400",
            hex: "#ef5350",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Red 500",
            hex: "#f44336",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Red 600",
            hex: "#e53935",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Red 700",
            hex: "#d32f2f",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Red 800",
            hex: "#c62828",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Red 900",
            hex: "#b71c1c",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Red a100",
            hex: "#ff8a80",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Red a200",
            hex: "#ff5252",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Red a400",
            hex: "#ff1744",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Red a700",
            hex: "#d50000",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Pinks",
        swatches: [
          {
            name: "Pink 50",
            hex: "#fce4ec",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Pink 100",
            hex: "#f8bbd0",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Pink 200",
            hex: "#f48fb1",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Pink 300",
            hex: "#f06292",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Pink 400",
            hex: "#ec407a",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Pink 500",
            hex: "#e91e63",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Pink 600",
            hex: "#d81b60",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Pink 700",
            hex: "#c2185b",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Pink 800",
            hex: "#ad1457",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Pink 900",
            hex: "#880e4f",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Pink a100",
            hex: "#ff80ab",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Pink a200",
            hex: "#ff4081",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Pink a400",
            hex: "#f50057",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Pink a700",
            hex: "#c51162",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Purples",
        swatches: [
          {
            name: "Purple 50",
            hex: "#f3e5f5",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Purple 100",
            hex: "#e1bee7",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Purple 200",
            hex: "#ce93d8",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Purple 300",
            hex: "#ba68c8",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Purple 400",
            hex: "#ab47bc",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Purple 500",
            hex: "#9c27b0",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Purple 600",
            hex: "#8e24aa",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Purple 700",
            hex: "#7b1fa2",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Purple 800",
            hex: "#6a1b9a",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Purple 900",
            hex: "#4a148c",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Purple a100",
            hex: "#ea80fc",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Purple a200",
            hex: "#e040fb",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Purple a400",
            hex: "#d500f9",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Purple a700",
            hex: "#aa00ff",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Deep Purples",
        swatches: [
          {
            name: "Deep Purple 50",
            hex: "#ede7f6",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Purple 100",
            hex: "#d1c4e9",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Purple 200",
            hex: "#b39ddb",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Purple 300",
            hex: "#9575cd",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Purple 400",
            hex: "#7e57c2",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Purple 500",
            hex: "#673ab7",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Purple 600",
            hex: "#5e35b1",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Purple 700",
            hex: "#512da8",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Purple 800",
            hex: "#4527a0",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Purple 900",
            hex: "#311b92",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Purple a100",
            hex: "#b388ff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Purple a200",
            hex: "#7c4dff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Purple a400",
            hex: "#651fff",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Purple a700",
            hex: "#6200ea",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Indigoes",
        swatches: [
          {
            name: "Indigo 50",
            hex: "#e8eaf6",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Indigo 100",
            hex: "#c5cae9",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Indigo 200",
            hex: "#9fa8da",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Indigo 300",
            hex: "#7986cb",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Indigo 400",
            hex: "#5c6bc0",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Indigo 500",
            hex: "#3f51b5",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Indigo 600",
            hex: "#3949ab",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Indigo 700",
            hex: "#303f9f",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Indigo 800",
            hex: "#283593",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Indigo 900",
            hex: "#1a237e",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Indigo a100",
            hex: "#8c9eff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Indigo a200",
            hex: "#536dfe",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Indigo a400",
            hex: "#3d5afe",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Indigo a700",
            hex: "#304ffe",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Blues",
        swatches: [
          {
            name: "Blue 50",
            hex: "#e3f2fd",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue 100",
            hex: "#bbdefb",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue 200",
            hex: "#90caf9",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue 300",
            hex: "#64b5f6",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue 400",
            hex: "#42a5f5",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue 500",
            hex: "#2196f3",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Blue 600",
            hex: "#1e88e5",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Blue 700",
            hex: "#1976d2",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Blue 800",
            hex: "#1565c0",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Blue 900",
            hex: "#0d47a1",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Blue a100",
            hex: "#82b1ff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue a200",
            hex: "#448aff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue a400",
            hex: "#2979ff",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Blue a700",
            hex: "#2962ff",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Light Blues",
        swatches: [
          {
            name: "Light Blue 50",
            hex: "#e1f5fe",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Blue 100",
            hex: "#b3e5fc",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Blue 200",
            hex: "#81d4fa",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Blue 300",
            hex: "#4fc3f7",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Blue 400",
            hex: "#29b6f6",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Blue 500",
            hex: "#03a9f4",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Light Blue 600",
            hex: "#039be5",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Light Blue 700",
            hex: "#0288d1",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Light Blue 800",
            hex: "#0277bd",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Light Blue 900",
            hex: "#01579b",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Light Blue a100",
            hex: "#80d8ff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Blue a200",
            hex: "#40c4ff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Blue a400",
            hex: "#00b0ff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Blue a700",
            hex: "#0091ea",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Cyans",
        swatches: [
          {
            name: "Cyan 50",
            hex: "#e0f7fa",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Cyan 100",
            hex: "#b2ebf2",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Cyan 200",
            hex: "#80deea",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Cyan 300",
            hex: "#4dd0e1",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Cyan 400",
            hex: "#26c6da",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Cyan 500",
            hex: "#00bcd4",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Cyan 600",
            hex: "#00acc1",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Cyan 700",
            hex: "#0097a7",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Cyan 800",
            hex: "#00838f",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Cyan 900",
            hex: "#006064",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Cyan a100",
            hex: "#84ffff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Cyan a200",
            hex: "#18ffff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Cyan a400",
            hex: "#00e5ff",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Cyan a700",
            hex: "#00b8d4",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Teals",
        swatches: [
          {
            name: "Teal 50",
            hex: "#e0f2f1",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Teal 100",
            hex: "#b2dfdb",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Teal 200",
            hex: "#80cbc4",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Teal 300",
            hex: "#4db6ac",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Teal 400",
            hex: "#26a69a",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Teal 500",
            hex: "#009688",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Teal 600",
            hex: "#00897b",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Teal 700",
            hex: "#00796b",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Teal 800",
            hex: "#00695c",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Teal 900",
            hex: "#004d40",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Teal a100",
            hex: "#a7ffeb",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Teal a200",
            hex: "#64ffda",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Teal a400",
            hex: "#1de9b6",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Teal a700",
            hex: "#00bfa5",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Greens",
        swatches: [
          {
            name: "Green 50",
            hex: "#e8f5e9",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Green 100",
            hex: "#c8e6c9",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Green 200",
            hex: "#a5d6a7",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Green 300",
            hex: "#81c784",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Green 400",
            hex: "#66bb6a",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Green 500",
            hex: "#4caf50",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Green 600",
            hex: "#43a047",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Green 700",
            hex: "#388e3c",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Green 800",
            hex: "#2e7d32",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Green 900",
            hex: "#1b5e20",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Green a100",
            hex: "#b9f6ca",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Green a200",
            hex: "#69f0ae",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Green a400",
            hex: "#00e676",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Green a700",
            hex: "#00c853",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Light Greens",
        swatches: [
          {
            name: "Light Green 50",
            hex: "#f1f8e9",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Green 100",
            hex: "#dcedc8",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Green 200",
            hex: "#c5e1a5",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Green 300",
            hex: "#aed581",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Green 400",
            hex: "#9ccc65",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Green 500",
            hex: "#8bc34a",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Light Green 600",
            hex: "#7cb342",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Light Green 700",
            hex: "#689f38",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Light Green 800",
            hex: "#558b2f",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Light Green 900",
            hex: "#33691e",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Light Green a100",
            hex: "#ccff90",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Green a200",
            hex: "#b2ff59",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Green a400",
            hex: "#76ff03",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Light Green a700",
            hex: "#64dd17",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Limes",
        swatches: [
          {
            name: "Lime 50",
            hex: "#f9fbe7",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Lime 100",
            hex: "#f0f4c3",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Lime 200",
            hex: "#e6ee9c",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Lime 300",
            hex: "#dce775",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Lime 400",
            hex: "#d4e157",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Lime 500",
            hex: "#cddc39",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Lime 600",
            hex: "#c0ca33",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Lime 700",
            hex: "#afb42b",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Lime 800",
            hex: "#9e9d24",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Lime 900",
            hex: "#827717",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Lime a100",
            hex: "#f4ff81",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Lime a200",
            hex: "#eeff41",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Lime a400",
            hex: "#c6ff00",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Lime a700",
            hex: "#aeea00",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Yellows",
        swatches: [
          {
            name: "Yellow 50",
            hex: "#fffde7",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow 100",
            hex: "#fff9c4",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow 200",
            hex: "#fff59d",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow 300",
            hex: "#fff176",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow 400",
            hex: "#ffee58",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow 500",
            hex: "#ffeb3b",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow 600",
            hex: "#fdd835",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow 700",
            hex: "#fbc02d",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow 800",
            hex: "#f9a825",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Yellow 900",
            hex: "#f57f17",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Yellow a100",
            hex: "#ffff8d",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow a200",
            hex: "#ffff00",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow a400",
            hex: "#ffea00",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Yellow a700",
            hex: "#ffd600",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Ambers",
        swatches: [
          {
            name: "Amber 50",
            hex: "#fff8e1",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Amber 100",
            hex: "#ffecb3",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Amber 200",
            hex: "#ffe082",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Amber 300",
            hex: "#ffd54f",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Amber 400",
            hex: "#ffca28",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Amber 500",
            hex: "#ffc107",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Amber 600",
            hex: "#ffb300",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Amber 700",
            hex: "#ffa000",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Amber 800",
            hex: "#ff8f00",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Amber 900",
            hex: "#ff6f00",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Amber a100",
            hex: "#ffe57f",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Amber a200",
            hex: "#ffd740",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Amber a400",
            hex: "#ffc400",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Amber a700",
            hex: "#ffab00",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Oranges",
        swatches: [
          {
            name: "Orange 50",
            hex: "#fff3e0",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Orange 100",
            hex: "#ffe0b2",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Orange 200",
            hex: "#ffcc80",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Orange 300",
            hex: "#ffb74d",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Orange 400",
            hex: "#ffa726",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Orange 500",
            hex: "#ff9800",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Orange 600",
            hex: "#fb8c00",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Orange 700",
            hex: "#f57c00",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Orange 800",
            hex: "#ef6c00",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Orange 900",
            hex: "#e65100",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Orange a100",
            hex: "#ffd180",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Orange a200",
            hex: "#ffab40",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Orange a400",
            hex: "#ff9100",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Orange a700",
            hex: "#ff6d00",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Deep Oranges",
        swatches: [
          {
            name: "Deep Orange 50",
            hex: "#fbe9e7",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Orange 100",
            hex: "#ffccbc",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Orange 200",
            hex: "#ffab91",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Orange 300",
            hex: "#ff8a65",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Orange 400",
            hex: "#ff7043",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Orange 500",
            hex: "#ff5722",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Orange 600",
            hex: "#f4511e",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Orange 700",
            hex: "#e64a19",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Orange 800",
            hex: "#d84315",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Orange 900",
            hex: "#bf360c",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Orange a100",
            hex: "#ff9e80",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Orange a200",
            hex: "#ff6e40",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Deep Orange a400",
            hex: "#ff3d00",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Deep Orange a700",
            hex: "#dd2c00",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Browns",
        swatches: [
          {
            name: "Brown 50",
            hex: "#efebe9",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Brown 100",
            hex: "#d7ccc8",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Brown 200",
            hex: "#bcaaa4",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Brown 300",
            hex: "#a1887f",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Brown 400",
            hex: "#8d6e63",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Brown 500",
            hex: "#795548",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Brown 600",
            hex: "#6d4c41",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Brown 700",
            hex: "#5d4037",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Brown 800",
            hex: "#4e342e",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Brown 900",
            hex: "#3e2723",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
      {
        name: "Blue-Grays",
        swatches: [
          {
            name: "Blue-Gray 50",
            hex: "#eceff1",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue-Gray 100",
            hex: "#cfd8dc",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue-Gray 200",
            hex: "#b0bec5",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue-Gray 300",
            hex: "#90a4ae",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue-Gray 400",
            hex: "#78909c",
            rgb: "",
            hsl: "",
            text: "#000000",
          },
          {
            name: "Blue-Gray 500",
            hex: "#607d8b",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Blue-Gray 600",
            hex: "#546e7a",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Blue-Gray 700",
            hex: "#455a64",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Blue-Gray 800",
            hex: "#37474f",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
          {
            name: "Blue-Gray 900",
            hex: "#263238",
            rgb: "",
            hsl: "",
            text: "#FFFFFF",
          },
        ],
      },
    ],
  },
];
